name: Deploy project
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: dotnet restore
      - name: Build project
        run: dotnet build
      - name: Deploy
        run: dotnet publish
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dotnet_artifact
          path: ./CovidStatistics/bin/Debug/net6.0/publish
